In [5]:
a=4.
b=5.

In [7]:
type(a+b)

float

In [8]:
type(3)

int

In [9]:
type(3.)

float

In [10]:
c=[1,2,3.4,3.8,8]

In [13]:
c[1]

2

In [14]:
len(c)

5

In [15]:
c[4]

8

In [16]:
c[5]

IndexError: list index out of range

In [17]:
c[1]**c[2]

10.556063286183154

In [19]:
#Este codigo define letras en las variables
d="Hola" #Esto es un string
e="Chau" 
d+e

'HolaChau'

In [21]:
d[1]

'o'

In [22]:
c+c

[1, 2, 3.4, 3.8, 8, 1, 2, 3.4, 3.8, 8]

In [27]:
g=2*c
print(g)

[1, 2, 3.4, 3.8, 8, 1, 2, 3.4, 3.8, 8]


In [25]:
f=d*2

In [26]:
print(f)

HolaHola


In [28]:
g[2:7]

[3.4, 3.8, 8, 1, 2]

In [29]:
g[2:]

[3.4, 3.8, 8, 1, 2, 3.4, 3.8, 8]

In [30]:
g[:7]

[1, 2, 3.4, 3.8, 8, 1, 2]

In [33]:
a=0
for l in g:
    a=a+l
print(a)

36.4


In [34]:
b=0
for l in range(100):
    b=b+2*l
print(b)
    

9900


In [39]:
for l in range(3,10,2):
    print(l)

3
5
7
9


In [40]:
for l in range(10,1,-2):
    print(l)

10
8
6
4
2


In [43]:
for k,l in enumerate(g):
    print("El elemento {} de la lista g es {}".format(k,l))

El elemento 0 de la lista g es 1
El elemento 1 de la lista g es 2
El elemento 2 de la lista g es 3.4
El elemento 3 de la lista g es 3.8
El elemento 4 de la lista g es 8
El elemento 5 de la lista g es 1
El elemento 6 de la lista g es 2
El elemento 7 de la lista g es 3.4
El elemento 8 de la lista g es 3.8
El elemento 9 de la lista g es 8


In [44]:
k

9

In [45]:
l

8

In [46]:
g.append("casa")

In [48]:
print(g)

[1, 2, 3.4, 3.8, 8, 1, 2, 3.4, 3.8, 8, 'casa']


In [49]:
g[10]="auto"

In [50]:
g

[1, 2, 3.4, 3.8, 8, 1, 2, 3.4, 3.8, 8, 'auto']

In [51]:
g[-1]="casa"

In [52]:
g

[1, 2, 3.4, 3.8, 8, 1, 2, 3.4, 3.8, 8, 'casa']

In [53]:
a=[2,3]
b=[4,5]
a+b

[2, 3, 4, 5]

In [54]:
import numpy as np
a_v=np.array(a)
b_v=np.array(b)
a_v+b_v

array([6, 8])

In [61]:
x = np.ones([3,2], dtype = float) 
print(x)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [62]:
np.random.uniform()

0.7193581281519982

In [63]:
np.random.uniform(9,14,[5,6])

array([[12.2380615 , 10.18214861, 12.4679735 , 10.47885113, 13.38881974,
        12.68842786],
       [11.87386522, 10.59741366, 10.67398133,  9.95116559, 11.65550095,
        13.34430942],
       [10.70068703, 12.76162319, 12.17030876,  9.13573108, 13.90757868,
         9.31425031],
       [12.31651178,  9.63357174,  9.29999993, 11.37083141, 10.75532145,
        12.77775861],
       [11.91741072, 13.83617479, 10.41250541, 10.46158685,  9.99645843,
        11.37348168]])

In [65]:
np.linalg.norm([1,1])

1.4142135623730951

Ejercicio 1

In [66]:
edad=39
print("Te faltan {} años para tener 100".format(100-39))

Te faltan 61 años para tener 100


In [70]:
num=34
if num % 2:
    print("El numero es impar")
else:
    print("El numero es par")

El numero es par


In [75]:
num=53
if num==53:
    print("Num es 53")
else:
    print("Num no es 53")

Num es 53


In [73]:
True + True

2

In [76]:
num=53
if num!=53:
    print("Num no es 53")
else:
    print("Num es 53")

Num es 53


In [78]:
del g[-1]

In [79]:
g

[1, 2, 3.4, 3.8, 8, 1, 2, 3.4, 3.8, 8]

In [80]:
for l in g:
    if l < 5:
        print(l)

1
2
3.4
3.8
1
2
3.4
3.8


In [81]:
f=[2,4,3.8,3.8,1,6,4]
h=list()
for l in g:
    for m in f:
        if l==m:
            print("Hola")

Hola
Hola
Hola
Hola
Hola
Hola
Hola
Hola


In [82]:
h=list()
h.append("3")

In [83]:
h

['3']

In [84]:
set(g)

{1, 2, 3.4, 3.8, 8}

In [85]:
h=[]

In [86]:
type(h)

list

In [89]:
import datetime
datetime.datetime.now()

datetime.datetime(2018, 7, 3, 21, 36, 15, 790752)

In [90]:
#Diccionario

dic={"Edad":39,"Nombre":"Carlos","Apellido":"Selmo"}

In [91]:
dic["Edad"]

39

In [92]:
dic[3.5]="Hola"

In [93]:
dic

{'Edad': 39, 'Nombre': 'Carlos', 'Apellido': 'Selmo', 3.5: 'Hola'}